# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import memory_scanner_pb2 as memory__scanner__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory_scanner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryScannerStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProcesses = channel.unary_unary(
                '/memory_scanner.MemoryScanner/ListProcesses',
                request_serializer=memory__scanner__pb2.Empty.SerializeToString,
                response_deserializer=memory__scanner__pb2.ProcessList.FromString,
                _registered_method=True)
        self.AttachToProcess = channel.unary_unary(
                '/memory_scanner.MemoryScanner/AttachToProcess',
                request_serializer=memory__scanner__pb2.ProcessRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.AttachResponse.FromString,
                _registered_method=True)
        self.DetachFromProcess = channel.unary_unary(
                '/memory_scanner.MemoryScanner/DetachFromProcess',
                request_serializer=memory__scanner__pb2.DetachRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.DetachResponse.FromString,
                _registered_method=True)
        self.ScanMemory = channel.unary_unary(
                '/memory_scanner.MemoryScanner/ScanMemory',
                request_serializer=memory__scanner__pb2.ScanRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ReadMemory = channel.unary_unary(
                '/memory_scanner.MemoryScanner/ReadMemory',
                request_serializer=memory__scanner__pb2.ReadRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.WriteMemory = channel.unary_unary(
                '/memory_scanner.MemoryScanner/WriteMemory',
                request_serializer=memory__scanner__pb2.WriteRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.FreezeValue = channel.unary_stream(
                '/memory_scanner.MemoryScanner/FreezeValue',
                request_serializer=memory__scanner__pb2.FreezeRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.FreezeStatus.FromString,
                _registered_method=True)
        self.UnfreezeValue = channel.unary_unary(
                '/memory_scanner.MemoryScanner/UnfreezeValue',
                request_serializer=memory__scanner__pb2.UnfreezeRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.Empty.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/memory_scanner.MemoryScanner/GetState',
                request_serializer=memory__scanner__pb2.StateRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.StateResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/memory_scanner.MemoryScanner/SyncState',
                request_serializer=memory__scanner__pb2.SyncRequest.SerializeToString,
                response_deserializer=memory__scanner__pb2.SyncResponse.FromString,
                _registered_method=True)


class MemoryScannerServicer(object):
    """Service definition
    """

    def ListProcesses(self, request, context):
        """Process operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachToProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachFromProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanMemory(self, request, context):
        """Memory scanning operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeValue(self, request, context):
        """Value freezing operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfreezeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """State synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcesses,
                    request_deserializer=memory__scanner__pb2.Empty.FromString,
                    response_serializer=memory__scanner__pb2.ProcessList.SerializeToString,
            ),
            'AttachToProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachToProcess,
                    request_deserializer=memory__scanner__pb2.ProcessRequest.FromString,
                    response_serializer=memory__scanner__pb2.AttachResponse.SerializeToString,
            ),
            'DetachFromProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachFromProcess,
                    request_deserializer=memory__scanner__pb2.DetachRequest.FromString,
                    response_serializer=memory__scanner__pb2.DetachResponse.SerializeToString,
            ),
            'ScanMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanMemory,
                    request_deserializer=memory__scanner__pb2.ScanRequest.FromString,
                    response_serializer=memory__scanner__pb2.ScanResponse.SerializeToString,
            ),
            'ReadMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMemory,
                    request_deserializer=memory__scanner__pb2.ReadRequest.FromString,
                    response_serializer=memory__scanner__pb2.ReadResponse.SerializeToString,
            ),
            'WriteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMemory,
                    request_deserializer=memory__scanner__pb2.WriteRequest.FromString,
                    response_serializer=memory__scanner__pb2.WriteResponse.SerializeToString,
            ),
            'FreezeValue': grpc.unary_stream_rpc_method_handler(
                    servicer.FreezeValue,
                    request_deserializer=memory__scanner__pb2.FreezeRequest.FromString,
                    response_serializer=memory__scanner__pb2.FreezeStatus.SerializeToString,
            ),
            'UnfreezeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfreezeValue,
                    request_deserializer=memory__scanner__pb2.UnfreezeRequest.FromString,
                    response_serializer=memory__scanner__pb2.Empty.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=memory__scanner__pb2.StateRequest.FromString,
                    response_serializer=memory__scanner__pb2.StateResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=memory__scanner__pb2.SyncRequest.FromString,
                    response_serializer=memory__scanner__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory_scanner.MemoryScanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory_scanner.MemoryScanner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryScanner(object):
    """Service definition
    """

    @staticmethod
    def ListProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/ListProcesses',
            memory__scanner__pb2.Empty.SerializeToString,
            memory__scanner__pb2.ProcessList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachToProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/AttachToProcess',
            memory__scanner__pb2.ProcessRequest.SerializeToString,
            memory__scanner__pb2.AttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachFromProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/DetachFromProcess',
            memory__scanner__pb2.DetachRequest.SerializeToString,
            memory__scanner__pb2.DetachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/ScanMemory',
            memory__scanner__pb2.ScanRequest.SerializeToString,
            memory__scanner__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/ReadMemory',
            memory__scanner__pb2.ReadRequest.SerializeToString,
            memory__scanner__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/WriteMemory',
            memory__scanner__pb2.WriteRequest.SerializeToString,
            memory__scanner__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreezeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/memory_scanner.MemoryScanner/FreezeValue',
            memory__scanner__pb2.FreezeRequest.SerializeToString,
            memory__scanner__pb2.FreezeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnfreezeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/UnfreezeValue',
            memory__scanner__pb2.UnfreezeRequest.SerializeToString,
            memory__scanner__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/GetState',
            memory__scanner__pb2.StateRequest.SerializeToString,
            memory__scanner__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_scanner.MemoryScanner/SyncState',
            memory__scanner__pb2.SyncRequest.SerializeToString,
            memory__scanner__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
