<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Target Name="CopyLibraryDependencies" AfterTargets="Build">
    <ItemGroup>
      <LibraryDependencies Include="$(NuGetPackageRoot)bootstrap\5.3.2\staticwebassets\**\*.*" />
      <LibraryDependencies Include="$(NuGetPackageRoot)font-awesome\6.5.1\staticwebassets\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(LibraryDependencies)"
          DestinationFiles="@(LibraryDependencies->'$(MSBuildProjectDirectory)\wwwroot\lib\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>