// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using BlazorFridaApp.Persistence;

#nullable disable

namespace BlazorFridaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250202194633_EnableForeignKeys")]
    partial class EnableForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");
        }
    }
}